name: Preview Deployment

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  deploy:
    uses: par-msl/metabyof/.github/workflows/deploy-reusable-npm.yml@main
    with:
      node-version: "22"
    permissions:
      id-token: write
      contents: read
      packages: read
      deployments: write
    secrets:
      VERCEL_TOKEN: ${{ secrets.METAAWS_VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.METAAWS_VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.METAAWS_VERCEL_PROJECT_ID }}
      AWS_ROLE_ARN: ${{ secrets.METAAWS_AWS_ROLE_ARN }}
      GH_TOKEN: ${{ secrets.METAAWS_GH_TOKEN }}
      VPC_CONFIG: ${{ secrets.METAAWS_VPC_CONFIG }}
